spring:
  application:
    name: my-restful-service
  messages:
    basename: messages

server:
  port: 8088

logging:
  level:
    org.springframework: debug

management:
  endpoints:
    web:
      exposure:
        include: "*" # 보안 이슈로 실사용은 특정 매트릭스만 지정 필요


